@Echo off

@REM PATH VARIABLES
SET "MAIN_SOURCE_JAVA_DIR=src\main\java\com\grupo11\GestionRecursosTecnologicos"
SET "ENTITIES_PACKAGE_DIR=%MAIN_SOURCE_JAVA_DIR%\persistance\entities"
SET "REPOSITORIES_PACKAGE_DIR=%MAIN_SOURCE_JAVA_DIR%\persistance\crud"
SET "CONTROLLERS_PACKAGE_DIR=%MAIN_SOURCE_JAVA_DIR%\web"
SET "SERVICES_PACKAGE_DIR=%MAIN_SOURCE_JAVA_DIR%\service"

SET "CLASS_NAME=%1"
SET "CLASS_ATRRIBUTES=%2"
SET "CLASS_CONTROLLER=%CLASS_NAME%Controller"
SET "CLASS_SERVICE=%CLASS_NAME%Service"
SET "CLASS_REPOSITORY=%CLASS_NAME%Repository"

@REM CODE INSTERTION VARIABLES
SET "CLASS_PACKAGE=package com.grupo11.GestionRecursosTecnologicos;"
SET "CLASS_CONSTRUCTOR=public %CLASS_NAME%() {}"
SET "CLASS_DECLARATION=public class %CLASS_NAME% {"

@REM FILE CREATION
type nul > ./%ENTITIES_PACKAGE_DIR%/%CLASS_NAME%.java
type nul > ./%REPOSITORIES_PACKAGE_DIR%/%CLASS_REPOSITORY%.java
type nul > ./%CONTROLLERS_PACKAGE_DIR%/%CLASS_CONTROLLER%.java
type nul > ./%SERVICES_PACKAGE_DIR%/%CLASS_SERVICE%.java

echo %CLASS_PACKAGE% >> ./%ENTITIES_PACKAGE_DIR%\%CLASS_NAME%.java
echo %CLASS_DECLARATION% >> ./%ENTITIES_PACKAGE_DIR%\%CLASS_NAME%.java

CALL :AddAtrributes %CLASS_ATRRIBUTES%

Echo %CLASS_CONSTRUCTOR% >> ./%ENTITIES_PACKAGE_DIR%\%CLASS_NAME%.java
Echo } >> ./%ENTITIES_PACKAGE_DIR%\%CLASS_NAME%.java

EXIT /B %errorlevel%

:AddAtrributes
IF NOT [%1] EQU [] (
    FOR /F "tokens=1* delims=," %%A IN (%1) DO (
        echo private %%A^; >> ./%ENTITIES_PACKAGE_DIR%\%CLASS_NAME%.java
        CALL :AddAtrributes "%%B"
    )
)
EXIT /B 0